//login
export var buttonSignIn = '.css-1m5rymt.e1w14daj6'
export var fsaIcon = '[src="https://images.prismic.io/axiance/ZDQ2MzNkNDUtNzZlYS00OTYwLTk0MTItYWQ4OWU1NmM5YjNl_6b22d204-7c05-44cb-b794-8be2346bc3c8_group4159.png?ixlib=gatsbyFP&q=50&auto=compress%2Cformat&rect=0%2C0%2C92%2C92&w=92&h=92"]'
export var cysecIcon = '[src="https://images.prismic.io/axiance/ODY5YTcwNTAtYjg2Ny00MjMxLWJhNTktNTAxOWYwY2RiN2Yx_68936e02-afac-41cc-a78d-8f15f3bf20ac_group4163.png?ixlib=gatsbyFP&q=50&auto=compress%2Cformat&rect=0%2C0%2C92%2C92&w=92&h=92"]'
export var newUrlFSA = 'https://client.axiance.com/int/sign-in?'
export var newUrlCySEC = 'https://client.axianceeu.com/sign-in?'
export var inputEmail = '#email'
export var inputPassword = '#password'
export var inputEnterPassword = '#repeatedPassword'
export var sideBar = '.styles_sidebar__8-r_L'
export var loginData = '.style_default__1exWx.style_s12__2GuCl'
//create trade acc
export var accountsTab= '.styles_itemText__2niJC'
export var createAccButton= '.style_button__1T3Pb.styles_button__3c_TI'
export var typeTradeAcc= '.style_checkboxText__GvthB'
export var platformType= '#platformType'
export var amount= '#amount'
export var leverage= '#leverage'
export var currency= '#currency'
export var value= '.css-13vhyk2-option'
export var tradeAccPasswordInput= '.style_wrapperInput__36oUg'
//open positions, pending positions, trading history and other actions
export var tab= '.styles_tabHeader__3Rgp7.styles_tabHeader__3fJiL'
export var tabActive= '.styles_tabHeader__3Rgp7.styles_tabHeader__3fJiL.styles_activeTabHeader__2UHMA'
export var tabLiveDemo= '.styles_tabHeader__3Rgp7.styles_tabHeader__18jRo'
export var buttonSwitch= '.style_button__1T3Pb.styles_switchButton__3wyvY'
export var buttonDeposit= '.style_button__1T3Pb.styles_singleDepositButton__8VDwo'
export var depositFunds= '.style_default__1exWx.style_s20__38iJt'
export var accSettings= '.styles_settingIcon__2__kK'
export var changePassword= '.styles_popOverButton__2It43'
export var textChangeYourPassword= '.style_default__1exWx.style_wb__2z8Ro.style_s20__38iJt'
export var buttonChange= '.style_button__1T3Pb.styles_submitButton__3yTMy'
export var summField= '#summ'
export var success= '.styles_popUpContentTitle__1rcnr'
export var buttonGoToPlatform = '.style_button__1T3Pb.styles_popUpContentButton__gjZCm'
export var container = '.styles_container__1O3h2'